name: publish-sphinx-to-gh-pages
on:
  push:
    branches:
    - master

jobs:
  build_sphinx_job:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install pip requirements
        run: pip install .[doc]
      - name: Sphinx build
        run: |
          git checkout -b gh-pages
          mkdir docs
          sphinx-build -b html doc/ docs
          touch docs/.nojekyll
      - name: Commit site
        run: |
          git config --global user.name 'D. V. Wiebe (automation)'
          git config --global user.email 'ketiltrout@users.noreply.github.com'
          git add .
          git commit -am "Automated sphinx build"
          git push --force origin gh-pages
